config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  namespace :admin do
    root "admins#login"
    resources :admins
    resources :categories
    resources :products
    resources :bills
    resources :product_bills
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  has_many :product_bills
  scope :find_by_bill, -> bill_id {where bill_id: bill_id}
  scope :get_bill_duration, -> end_renting{
    (end_renting - Date.current()).to_s.split("/")[0].to_i
  }
end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :items

def add_item(product_id)
    if item
        # increase the quantity of product in cart
        count + 1
        save
    else
        # product does not exist in cart
        product = Product.find(product_id)
        items << product
    end
    save
end

def total_price
    items.to_a.sum(&:full_price)
end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/system/categories/images/default-image.png"
    validates_attachment :image, presence: true
    do_not_validate_attachment_file_type :image
    validates :name, presence: true

    #apply default scope for all query of Category
    default_scope {where is_deleted: false}
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  scope :find_by_products, -> category_id {where category_id: category_id }
  has_many :product_sizes
  has_many :product_bills
  enum status: [:remove,:active]
  has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  accepts_nested_attributes_for :product_sizes,
  reject_if: proc { |attrs| attrs[:size_id].blank? }
end

app/models/product_bill.rb
class ProductBill < ApplicationRecord
  belongs_to :product
  belongs_to :bill
  belongs_to :size
  scope :find_by_billid, -> id {where bill_id: id }
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  belongs_to :product
  belongs_to :size
  # Attributes: color:string, quantity:integer, note:string
end

app/models/size.rb
class Size < ApplicationRecord
    has_many :product_sizes
    has_many :product_bills
    accepts_nested_attributes_for :product_sizes
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :bills
  scope :find_by_role,  -> role_number {where role: role_number}

end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
  before_action :login_success, except: :destroy
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      log_in user
      redirect_to admin_categories_path, :notice => ["Đăng nhập thành công!", "success"]
    else
      redirect_to admin_root_path, :notice => ["Đăng nhập sai!", "error"]
    end
  end
  def destroy
    log_out
    redirect_to admin_root_path, :notice => ["Đăng xuất thành công!", "success"]
  end

end

app/controllers/admin/bills_controller.rb
class Admin::BillsController < Admin::ApplicationController
  def index
    @q = Bill.ransack(params[:q])
    if @q
      @bills = @q.result.includes(:user).page(params[:page]).per(10)
    else
      @bills = Bill.all.page(params[:page]).per(10)
      @bill = Bill.new
      @bill = User.new
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
    @bill = Bill.find_by_id(params[:id])
    @user = @bill.user
    @products_id = ProductBill.find_by_billid(@bill.id).distinct.pluck("product_id")
    @products_number = ProductBill.find_by_billid(@bill.id).group(:product_id).count()
    @products_name = []
    @products_price = []
    @products_id.each do |id|
      @p= Product.find_by_id(id)
      @products_name.push(@p.name)
      @products_price.push(@p.price)
    end
    respond_to do |format|
      format.js { }
    end
  end

  def new

  end

  def create
    respond_to do |format|
      format.js{}
    end
  end

end

app/controllers/admin/carts_controller.rb
class Admin::CartsController < Admin::ApplicationController
  def show
    @cart = current_cart
  end
  def add_to_cart
    current_cart.add_item(params[:product_id])
    # redirect to shopping cart or whereever
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def show
    @bill = Bill.find_by id: params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def new
        @category = Category.new
    end

    def create
        @category = Category.new(params.require(:category).permit(:name, :image))
        @category.save
        redirect_to admin_category_path(@category)
    end

    def show
        @category = Category.find_by(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by id: params[:id]` 
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/product_bills_helper.rb
module ProductBillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/bills/_modal.html.erb
<div class="container">
  <div class="modal fade" id="modal-default">
    <div class="modal-dialog modal-lg" id="data-modal">
      <%= render "modalcontent" %>
    </div>
  </div>
</div>
</div>

app/views/admin/bills/_modalcontent.html.erb
<% if (@bill != nil && @user != nil) %>
<div class="modal-content">
  <div class="modal-header">
    <button class="btn-edit" onclick="enableEdit()">
      <i class="fa fa-2x fa-edit icon-edit"></i>
    </button>
  </div>
  <div class="modal-body">
    <div class="box-body no-padding info-bill">
      <div class="row row-info">
        <div class="col-xs-6">
          <strong><%= t "admin.bills.name" %>:</strong>
          <input class="show-data show-data-edit" type="text" value=<%= @user.name %> disabled="disabled"/>
        </div>
        <div class="col-xs-6">
          <strong><%= t "admin.bills.start_renting" %>:</strong>
          <input class='date-picker' type="text" data-provide='datepicker' value= <%= @bill.start_renting %> disabled="disabled"/>
        </div>
        <div class="col-xs-6">
          <strong><%= t "admin.bills.phone_number" %>:</strong>
          <input class="show-data" type="text" value=<%= @user.phone %> disabled="disabled"/>
        </div>
        <div class="col-xs-6">
          <strong><%= t "admin.bills.end_renting" %>:</strong>
          <input class='date-picker' type="text" data-provide='datepicker' value=<%= @bill.end_renting %> disabled="disabled"/>
        </div>
        <div class="col-xs-6">
          <strong><%= t "admin.bills.personal_card" %>:</strong>
          <input class="show-data" type="text" value=<%= @user.personal_card %> disabled="disabled"/>
        </div>
        <div class="col-xs-6">
          <strong><%= t "admin.bills.extend_renting" %>:</strong>
          <input class="show-data" type="text" value="none" disabled="disabled"/>
        </div>
      </div>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-bill table-hover">
        <thead class="scrollhead">
        <tr class="row">
          <th class="col-md-2"><%= t "admin.bills.id" %></th>
          <th class="col-md-2"><%= t "admin.products.product_name" %></th>
          <th class="col-md-2"><%= t "admin.bills.quantity" %></th>
          <th class="col-md-2"><%= t "admin.products.price" %></th>
          <th class="col-md-2"><%= t "admin.bills.total" %></th>
          <th class="col-md-2"><%= t "admin.bills.remove" %></th>
        </tr>
        </thead>
        <tbody class="scrollbody">
        <% @products_id.each_with_index do |item, index| %>
        <tr class="row">
          <td class="col-md-2"><%= index + 1 %></td>
          <td class="col-md-2"><%= @products_name[index] %></td>
          <td class="col-md-2"><%= @products_number[item] %></td>
          <td class="col-md-2"><%= @products_price[index] %></td>
          <td class="col-md-2"><%= @products_number[item].to_f*@products_price[index].to_f %></td>
          <td class="col-md-2">
            <a href="#" class="remove-bill"><%= t "admin.bills.remove" %></a>
          </td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="row total-bill">
      <div class="col-xs-4">
        <strong><%= t "admin.bills.total_money" %>: <%= @bill.total %></strong>
      </div>
      <div class="col-xs-4">
        <strong><%= t "admin.bills.extend" %>:</strong><br>
      </div>
      <div class="col-xs-4">
        <strong><%= t "admin.bills.total_fee" %>: <%= @bill.total %></strong>
      </div>
    </div>
  </div>
  <div class="modal-footer footer-bill">
    <button type="button" class="btn btn-danger" data-dismiss="modal"><%= t "admin.bills.btn_pay" %></button>
    <button type="button" class="btn btn-danger btn-cancel" onclick="disableEdit()" data-dismiss="modal"><%= t "admin.bills.btn_cancel" %></button>
  </div>
</div>
<% end %>

app/views/admin/bills/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Danh sách hóa đơn</h3>
        <%= search_form_for @q, url: admin_bills_path(@q) do |f| %>
        <div class="input-group input-group-sm search-box" style="width: 150px;">
          <%= f.text_field :user_name_start, type: "text",class: "form-control pull-right", placeholder: "Search" %>
          <div class="input-group-btn">
              <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        <% end %>
        </div>
      </div>
      <div class="box-body table-responsive no-padding table">
        <table class="table table-hover">
          <tr>
            <th>STT</th>
            <th>Tên khách hàng</th>
            <th>Ngày thuê</th>
            <th>Tổng phí</th>
            <th>IDCard</th>
            <th>Hiện trạng</th>
            <th>Xem chi tiết</th>
          </tr>
          <% @bills.each do |bill| %>
          <tr>
            <td><%= bill.id %></td>
            <td><%= bill.user.name %></td>
            <td><%= bill.start_renting %></td>
            <td><%= bill.total %></td>
            <td><%= bill.user.personal_card %></td>
            <td>
              <%= content_tag :span, :class => (
                case bill.status
                  when 0
                    "label label-success"
                  when 1
                    "label label-default"
                  when 2
                    "label label-danger"
                  when 4
                    "label label-warning"
                  end
                ) do %>
                <%= Bill.get_bill_duration(bill.end_renting)  %>
              <% end %>
            </td>
            <td><%= link_to "", admin_bill_path(bill), remote: true, :method => :get, :class => "btn btn-default fa fa-eye","data-toggle" => "modal", "data-target" => "#modal-default" %></td>
          </tr>
          <% end %>
        </table>
      </div>
      <div class="box-footer clearfix paginate">
        <p>
          <%= page_entries_info @bills %>
          <%= paginate @bills, theme: "twitter-bootstrap-4" %>
        </p>
      </div>
    </div>
  </div>
</div>
 <tbody id="bills">
  <%= render "modal" %>
</tbody>

app/views/admin/bills/show.js.erb
$("#data-modal").html("<%= j render 'modalcontent', bill: @bill %>");

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
    STT:
       <%= f.text_field :user_id %>
	   <Br>
    Ngày thuê:
       <%= f.text_field :start_renting %>
	   <Br>
	Ngày trả:
       <%= f.text_field :end_renting %>
	   <Br>
    Tổng phí:
	   <%= f.text_field :total %>
	   <Br>
	Hiện trạng:
	   <%= f.text_field :status %>
	   <Br>
    <%= f.submit  "Submit" %>             
<% end %>

app/views/bills/index.html.erb
 <div class="box-body table-responsive no-padding table">
    <table class="table table-hover">
        <tr>
            <th>STT</th>	
            <th>Ngày thuê</th>
            <th>Ngày trả</th>
            <th>Tổng phí</th>
            <th>Hiện trạng</th>
        </tr>
        <% @bills.each do |bill| %>
        <tr class="info">
            <td><%= bill.id %></td>
            <td><%= bill.end_renting %></td>
            <td><%= bill.start_renting %></td>
            <td><%= bill.total %></td>
            <td><span class="label label-success"><%= bill.status %></span></td>
        </tr>
        <tr class="danger">
            <td><%= bill.id %></td>
            <td><%= bill.end_renting %></td>
            <td><%= bill.start_renting %></td>
            <td><%= bill.total %></td>
            <td><span class="label label-warning"><%= bill.status %></span></td>
        </tr>
        <tr class="active">
            <td><%= bill.id %></td>
            <td><%= bill.end_renting %></td>
            <td><%= bill.start_renting %></td>
            <td><%= bill.total %></td>
            <td><span class="label label-primary"><%= bill.status %></span></td>
        </tr>
        <tr class="sucess">
            <td><%= bill.id %></td>
            <td><%= bill.end_renting %></td>
            <td><%= bill.start_renting %></td>
            <td><%= bill.total %></td>
            <td><span class="label label-danger"><%= bill.status %></span></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/bills/new.html.erb
<h1>New Bill</h1>
<%= render 'form', bill: @bill %>

app/views/bills/show.erb
<% provide(:title, "showBill") %>
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
 
</head>
<body>
<div class="container">
  <!-- Button to Open the Modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    view details bill
  </button>
  <!-- The Modal -->
  <div class="modal fade" id="myModal">
    <div class="view-bill modal-dialog">
      <div class="modal-content">
        <!-- Modal Header -->
        <!-- Modal body -->
        <div class="modal-body">
          <i class="fa fa-edit"></i>  
          <div class="box-body no-padding info-bill">
            <div class="row row-info-first">
              <div class="col-6">
                <strong>Tên:</strong>
                <%= Bill.first.user.name %>
              </div>
              <div class="col-6">
                <strong>Ngày thuê:</strong>
                <input type="text" id='datepicker' class='datepicker' placeholder='yyyy-mm-dd' value= <%= Bill.first.start_renting %> />
                <script>
                  $('#datepicker').datepicker({format: 'yyyy-mm-dd'});
                </script>
              </div>
              <div class="col-6">
                <strong>Số điện thoại:</strong>
              </div>
              <div class="col-6">
                <strong>Ngày hết hạn:</strong>
                <input type="text" id='datepicker' class='datepicker--expiredate' placeholder='yyyy-mm-dd' value= <%= Bill.first.end_renting %> />
                <script>
                  $('#datepicker').datepicker({format: 'yyyy-mm-dd'});
                </script>
              </div>
              <div class="col-6">
                <strong>Thẻ cá nhân:</strong>
                <%= Bill.first.user.personal_card %>
              </div>
              <div class="col-6">
                <strong>Ngày gia hạn:</strong>
                <%# <%= Bill.first.start_renting %>
              </div>
            </div>
              <table class="table table-bordered table-bill table-hover">
                <tr>
                  <th>ID</th>
                  <th>Sản phẩm</th>
                  <th>Sô lượng</th>
                  <th>Giá</th>
                  <th>Tổng tiền</th>
                  <th>remove</th>
                </tr>
                  <tr>
                    <td><%= Bill.first.user.id %></td>
                    <td>Váy đuôi cá</td>
                    <td>1</td>
                    <td>500 000</td>
                    <td>500 000</td>
                    <td><a class="remove-bill">Remove</a></td>
                  </tr>
                  <tr>
                    <td><%= Bill.first.user.id %></td>
                    <td>Váy đuôi cá</td>
                    <td>1</td>
                    <td>500 000</td>
                    <td>500 000</td>
                    <td><a class="remove-bill">Remove</a></td>
                  </tr>
              </table>
            </div>
            <div class="row row-info-second">
              <div class="col-2">
                <strong>Tổng tiền:</strong><br>
              </div>
              <div class="col-2">
                <strong>Gia hạn:</strong><br>
              </div>
              <div class="col-2">
                <strong>Thành tiền:</strong>
              </div>
          </div>
        </div>        
        <!-- Modal footer -->
        <div class="modal-footer footer-bill">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Pay</button>
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
        </div>        
      </div>
    </div>
  </div>  
</div>
</body>
</html>

app/views/bills/show.html.erb
<p id="notice">
    <%= notice %>
</p>
<table class="table">
	<thead>
		<tr>
		    <th>STT</th>
			<th>Ngày thuê</th>
			<th>Ngày trả</th>
			<th>Tổng phí</th>
			<th>Hiện trạng</th>	
		</tr>
	</thead>
	<tbody>  
		<tr class="success">
		    <td><%= @bill.id %></td>
		    <td><%= @bill.start_renting %></td>
			<td><%= @bill.end_renting %></td>
			<td><%= @bill.total %></td>
			<td><%= @bill.status %></td>
		</tr>
	</tbody>
</table>