config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  namespace :admin do
    root "admins#login"
    resources :admins
    resources :categories
    resources :products
    resources :bills
    resources :product_bills
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  has_many :product_bills
  scope :find_by_bill, -> bill_id {where bill_id: bill_id}
  scope :get_bill_duration, -> end_renting{
    (end_renting - Date.current()).to_s.split("/")[0].to_i
  }
end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :items

def add_item(product_id)
    if item
        # increase the quantity of product in cart
        count + 1
        save
    else
        # product does not exist in cart
        product = Product.find(product_id)
        items << product
    end
    save
end

def total_price
    items.to_a.sum(&:full_price)
end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/system/categories/images/default-image.png"
    validates_attachment :image, presence: true
    do_not_validate_attachment_file_type :image
    validates :name, presence: true

    #apply default scope for all query of Category
    default_scope {where is_deleted: false}
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  scope :find_by_products, -> category_id {where category_id: category_id }
  has_many :product_sizes
  has_many :product_bills
  enum status: [:remove,:active]
  has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  accepts_nested_attributes_for :product_sizes,
  reject_if: proc { |attrs| attrs[:size_id].blank? }
end

app/models/product_bill.rb
class ProductBill < ApplicationRecord
  belongs_to :product
  belongs_to :bill
  belongs_to :size
  scope :find_by_billid, -> id {where bill_id: id }
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  belongs_to :product
  belongs_to :size
  # Attributes: color:string, quantity:integer, note:string
end

app/models/size.rb
class Size < ApplicationRecord
    has_many :product_sizes
    has_many :product_bills
    accepts_nested_attributes_for :product_sizes
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :bills
  scope :find_by_role,  -> role_number {where role: role_number}

end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
  before_action :login_success, except: :destroy
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      log_in user
      redirect_to admin_categories_path, :notice => ["Đăng nhập thành công!", "success"]
    else
      redirect_to admin_root_path, :notice => ["Đăng nhập sai!", "error"]
    end
  end
  def destroy
    log_out
    redirect_to admin_root_path, :notice => ["Đăng xuất thành công!", "success"]
  end

end

app/controllers/admin/bills_controller.rb
class Admin::BillsController < Admin::ApplicationController
  def index
    @q = Bill.ransack(params[:q])
    if @q
      @bills = @q.result.includes(:user).page(params[:page]).per(10)
    else
      @bills = Bill.all.page(params[:page]).per(10)
      @bill = Bill.new
      @bill = User.new
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
    @bill = Bill.find_by_id(params[:id])
    @user = @bill.user
    @products_id = ProductBill.find_by_billid(@bill.id).distinct.pluck("product_id")
    @products_number = ProductBill.find_by_billid(@bill.id).group(:product_id).count()
    @products_name = []
    @products_price = []
    @products_id.each do |id|
      @p= Product.find_by_id(id)
      @products_name.push(@p.name)
      @products_price.push(@p.price)
    end
    respond_to do |format|
      format.js { }
    end
  end

  def new

  end

  def create
    respond_to do |format|
      format.js{}
    end
  end

end

app/controllers/admin/carts_controller.rb
class Admin::CartsController < Admin::ApplicationController
  def show
    @cart = current_cart
  end
  def add_to_cart
    current_cart.add_item(params[:product_id])
    # redirect to shopping cart or whereever
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :load_category, only: [:destroy, :edit, :update]
  def index
    @categories = Category.order(id: :desc).page(params[:page]).per(5)
  end

  def new
    @category = Category.new
  end

  def create
    respond_to do |format|
      if @category = Category.create(category_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @category.errors.full_messages,
                            status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.update(is_deleted: true)
    if @category.is_deleted
      redirect_to admin_categories_path, :notice => ["Xóa thành công", "success"]
    else
      redirect_to admin_categories_path, :notice => ["Xóa không thành công", "error"]
    end
  end

  def edit
  end

  def update
    respond_to do |format|
     if @category.update(category_params)
       format.json { head :no_content }
       format.js
     else
       format.json { render json: @category.errors.full_messages,
                                  status: :unprocessable_entity }
     end
   end
 end

  private

  def load_category
    @category = Category.find_by id: params[:id]
  end

  def category_params
    params.permit(:name, :image)
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def show
    @bill = Bill.find_by id: params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def new
        @category = Category.new
    end

    def create
        @category = Category.new(params.require(:category).permit(:name, :image))
        @category.save
        redirect_to admin_category_path(@category)
    end

    def show
        @category = Category.find_by(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by id: params[:id]` 
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/product_bills_helper.rb
module ProductBillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/_category.html.erb
<div class="row-item">
  <div class="col-md-3 col-sm-6 col-xs-12" id="category_<%= category.id %>">
    <div class="box-category">
      <div class="category-content">
          <%= link_to admin_products_path(:category_id => category.id) do %>
          <img  class="image-category" src="<%= category.image %>" alt="Material Dashboard Pro">
          <span class="name-category"><%= category.name %></span>
          <%end%>
        <div class = "btn-group btn-categories-controller">
          <%= link_to edit_admin_category_path(category), remote: true, :class => 'btn btn-default' do %>
          <i class="fa fa-edit"></i>
          <%end%>
          <button type="button" class="btn btn-default" data-toggle="modal" data-target="#deleteCategory<%=category.id%>"><i class="fa fa-trash"></i></button>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="deleteCategory<%=category.id%>" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><%= t "admin.categories.del_confirm_title" %></h4>
        </div>
        <div class="confirm-delete">
          <p><%= t "admin.categories.del_confirmation"%><%=category.name%>?</p>
        </div>
        <div class="modal-footer">
          <%= link_to admin_category_path(category),method: :delete,
          data: {} do %>
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= t "admin.categories.del" %></button>
          <% end %>
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= t "admin.categories.close" %></button>
        </div>
      </div>
    </div>
  </div>

app/views/admin/categories/_edit.html.erb
<div class="modal fade" id="editCategory<%=c.id%>" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%=t "admin.categories.create_title"%></h4>
      </div>
      <div class="modal-body">
        <div class = "container">
          <%= form_for(c, url: admin_categories_path) do |form| %>
            <%= render  "form", c: c, form: form %>
          <% end %>
        <button type="button" class="btn btn-default" data-dismiss="modal"><%=t "admin.categories.close"%></button>
      </div>
    </div>
  </div>
</div>
<script>
  var loadFile = function(event) {
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
  };
</script>

app/views/admin/categories/_form.html.erb
<div class = "container">
  <%= form_for([:admin, @category], remote: true, :html => { :role => "form" }) do |form| %>
    <div class = "row">
      <div class = "col-md-3">
        <div class = "row"><%= form.text_field :name, :placeholder => t("admin.categories.name"),
          class:"category__name_field", name: "name" %></div>
        <div class = "row">
          <label for="exampleInputFile"><%=t "admin.categories.add_image"%></label>
          <%= form.file_field :image, type:"file", onchange: "loadFile(event)", name: "image"%>
        </div>
      </div>
      <div class="preview col-md-3">
        <img id = "output" src = <%= @category.image%> />
      </div>
    </div>
    <div class="modal-footer btn-group-category">
      <%= form.submit t("admin.categories.save"), type:"submit", class: "btn btn-primary btn-category" %>
      <button type="button" class="btn btn-default btn-category" data-dismiss="modal"><%=t "admin.categories.close"%></button>
    </div>
<% end %>
</div>
<script type = "text/javascript">
  var loadFile = function(event) {
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
  };
  $(function() {
    var notice = "<%= !flash[:notice].nil? ? flash[:notice].first : ''%>"
    var type = "<%= !flash[:notice].nil? ? flash[:notice].last : ''%>"
    $.notify(notice, type);
  });

</script>

app/views/admin/categories/_new.html.erb
<div class="modal fade" id="newCategory" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%=t "admin.categories.create_title"%></h4>
      </div>
      <div class="modal-body">
        <div class = "container">
          <%= form_for(category, url: admin_categories_path) do |form| %>
            <%= render  "form", form: form %>
          <% end %>
        <button type="button" class="btn btn-default" data-dismiss="modal"><%=t "admin.categories.close"%></button>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/edit.js.erb
// Add the dialog title
$('#modal h4').html('<i class="glyphicon glyphicon-pencil"></i><%= t "admin.categories.edit_category"%>');

// Render the edit form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#modal').modal("show");
  $(".edit_category").validate({
    rules: {
      name: {
        required: true,
        minlength: 2
              },
      image: {
        required: false,
              }
    },
    messages: {
      name: {
        required: "Vui lòng nhập tên Danh mục",
        minlength: "Ngắn quá!!"
              },
    }
  });

app/views/admin/categories/index.html.erb
<div class="row docs-premium-template">
  <% @categories.each do |c| %>
    <div class="col-sm-12 col-md-4">
      <div class="box box-solid">
        <div class="box-body" style= "height: 450px;">
          <div class = "btn-group categories-controller">
            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#editCategory<%=c.id%>"><i class="fa fa-edit"></i></button>
              <%= render  "edit", c:c %>
            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#deleteCategory"><i class="fa fa-trash"></i></button>
          </div>
          <div class="media">
            <div class="media-left">
              <a href="#" class="ad-click-event">
                <img src="<%= c.picture %>" alt="Material Dashboard Pro" class="media-object">
              </a>
            </div>
          </div>
          <h4 class = "category-title">
            <%= c.name %>
          </h4>
        </div>
      </div>
    </div>
  <% end %>
    <div class="col-sm-12 col-md-4 add-category__btn" style= "height: 450px;">
      <div class="container">
        <!-- Trigger the modal with a button -->
        <button type="button" class="btn btn-info btn-lg btn__add" data-toggle="modal" data-target="#newCategory"><i class="fa fa-plus"></i> </button>
        <%= render  "new", category: @new_category %>
      </div>
    </div>
</div>
<div class="row paginate">
  <%= paginate @categories, theme: 'twitter-bootstrap-4' %>
</div>

app/views/admin/categories/new.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-3 "
    <div class="box box-info">
      <div class="box-header with-border">
        <h3 class="box-title">Tạo Loại Mới</h3>
      </div>
    <!-- /.box-header -->
    <!-- form start -->
      <%= form_for [:admin, @category], url: {action:"create"},html: {class:"form-horizontal"} do |f| %>
        <div class="box-body">
          <div class="form-group">
            <%= f.label :Tên, for:"inputEmail3", class:"col-sm-2 control-label" %>

            <div class="col-sm-10">
              <%= f.text_field :name, class:"form-control", id:"inputEmail3", placeholder:"Name" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :Ảnh, for:"inputPassword3", class:"col-sm-2 control-label" %>

            <div class="col-sm-10">
              <%= f.file_field :image, class:"form-control", id:"inputPassword3", placeholder:"Image" %>
            </div>
          </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <button type="submit" class="btn btn-info pull-right">Save</button>
        </div>
        <!-- /.box-footer -->
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/new.js.erb
//Show modal
$('#modal').modal("show");

// Add the dialog title
$('#modal h4').html('<i class="glyphicon glyphicon-plus"></i><%= t "admin.categories.create_title" %>');

// Render the new form
$('.modal-body').html('<%= j render("form") %>');

//Validation for method new
$("#new_category").validate({
    rules: {
      name: {
        required: true,
        minlength: 2
              },
        image: "required",
    },
    messages: {
      name: {
        required: "Vui lòng nhập tên Danh mục",
        minlength: "Ngắn quá!!"
              },
        image: "Vui lòng chọn ảnh",
    }
  });

app/views/admin/categories/show.html.erb
<p>
    <%= image_tag @category.image.url %><br/>
    <strong>Name:</strong>
    <%= @category.name %>
</p>
<%= link_to 'Back', new_admin_category_path%>