config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  namespace :admin do
    root "admins#login"
    resources :admins
    resources :categories
    resources :products
    resources :bills
    resources :product_bills
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  has_many :product_bills
  scope :find_by_bill, -> bill_id {where bill_id: bill_id}
  scope :get_bill_duration, -> end_renting{
    (end_renting - Date.current()).to_s.split("/")[0].to_i
  }
end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :items

def add_item(product_id)
    if item
        # increase the quantity of product in cart
        count + 1
        save
    else
        # product does not exist in cart
        product = Product.find(product_id)
        items << product
    end
    save
end

def total_price
    items.to_a.sum(&:full_price)
end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/system/categories/images/default-image.png"
    validates_attachment :image, presence: true
    do_not_validate_attachment_file_type :image
    validates :name, presence: true

    #apply default scope for all query of Category
    default_scope {where is_deleted: false}
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  scope :find_by_products, -> category_id {where category_id: category_id }
  has_many :product_sizes
  has_many :product_bills
  enum status: [:remove,:active]
  has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  accepts_nested_attributes_for :product_sizes,
  reject_if: proc { |attrs| attrs[:size_id].blank? }
end

app/models/product_bill.rb
class ProductBill < ApplicationRecord
  belongs_to :product
  belongs_to :bill
  belongs_to :size
  scope :find_by_billid, -> id {where bill_id: id }
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  belongs_to :product
  belongs_to :size
  # Attributes: color:string, quantity:integer, note:string
end

app/models/size.rb
class Size < ApplicationRecord
    has_many :product_sizes
    has_many :product_bills
    accepts_nested_attributes_for :product_sizes
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :bills
  scope :find_by_role,  -> role_number {where role: role_number}

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
	before_action :get_product, only: [:show, :edit, :update, :destroy]
	before_action :load_categories, only: [:index, :edit, :new, :update]
	before_action :load_sizes, only: [:index, :edit, :new, :update]
	def index
		if(params[:search].present?)
			q = params[:search]
			products = Product.where(status: :active).search(name_cont: q).result.page(params[:page]).order(id: :desc).per(12)
			@products = products
			@action = true
			respond_to do |format|
				format.js
				format.html
			end
		else
			@products = Product.all.page(params[:page]).per(12)
			@categories = Category.all
			if params[:category_id] != nil
				@products = Product.where(status: :active).find_by_products(params[:category_id]).order(id: :desc).page(params[:page]).per(12)
			else
				@products = Product.where(status: :active).find_by_products(1).page(params[:page]).order(id: :desc).per(12)
	    end
		end
	end
	def new
		@product = Product.new
		4.times do
      @product.product_sizes.build
    end
  end

	def create
     @product = Product.new(product_params)
		 respond_to do |format|

      if @product.save
        format.js
      else
        format.json { render json: @product.errors.full_messages,
                            status: :unprocessable_entity }
      end

    end
  end

  def show
    @product_size = @product.product_sizes
  end

  def edit
    @product_size = @product.product_sizes
  end

  def update
		respond_to do |format|
      if @product.update(product_params)
				format.js
      else
        format.json { render json: @product.errors.full_messages,
					status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if (Product.update(params[:id],:status => "remove"))
			flash[:notice] = [t("admin.products.notice_delete"), "success"]
			if params[:category_id] != nil
        @products = Product.where(status: :active).find_by_products(params[:category_id]).order(id: :desc).page(params[:page]).per(12)
			else
        @products = Product.where(status: :active).find_by_products(1).order(id: :desc).page(params[:page]).per(12)
			end
			params[:id] = ""
    end
  end

	private
		def get_product
			@product = Product.find_by id: params[:id]
		end
    def product_params
      params.require(:product).permit(:image, :name, :price, :renting_fee, :category_id,
			product_sizes_attributes: [:product_id, :size_id, :size_name, :color, :quantity, :note])
    end
		def load_categories
			@categories = Category.all
		end
		def load_sizes
			@sizes = Size.all
		end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def show
    @bill = Bill.find_by id: params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def new
        @category = Category.new
    end

    def create
        @category = Category.new(params.require(:category).permit(:name, :image))
        @category.save
        redirect_to admin_category_path(@category)
    end

    def show
        @category = Category.find_by(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by id: params[:id]` 
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/product_bills_helper.rb
module ProductBillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product], remote: true, :html => { :role => "form" })  do |p| %>
<div class="modal-body body-add-product">
  <div class="form-group">
    <div class="preview col-md-3 add-image">
      <label for="exampleInputFile"><%= t "admin.products.add_picture" %></label>
      <div >
        <%= p.file_field :image%>
      </div>
    </div>
    <div class="preview col-md-9 add-item">
      <form class="add-form">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label "><%= t "admin.products.category_name" %></label>
          <div class=" text col-sm-10">
            <%= p.select :category_id, @categories.collect { |u| [ u.name, u.id ] },{}, {class: "select-category"} %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label"><%= t "admin.products.name" %></label>
          <div class="col-sm-10">
            <%= p.text_field :name, class: "input-text" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label"><%= t "admin.products.price" %></label>
          <div class="col-sm-10">
            <%= p.text_field :price, class: "input-text" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label"><%= t "admin.products.renting_fee" %></label>
          <div class="col-sm-10">
            <%= p.text_field :renting_fee, class: "input-text" %>
          </div>
        </div>
        <%= p.fields_for :product_sizes do |product_size| %>
          <%= render "product_size", product_size: product_size %>
        <%end%>
        <div class="form-group">
          <button type="button" class="btn-back btn btn-default pull-left" data-dismiss="modal"><%= t "admin.products.btn_back" %></button>
          <%= p.submit t("admin.products.btn_save"), class:" btn btn-primary btn-save" %>
        </div>
      </form>
    </div>
  </div>
</div>
<%end%>

app/views/admin/products/_new.html.erb
<div class="modal fade" id="modal-default">
  <div class="modal-dialog">
    <div class="modal-content modal-add-product">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= t "admin.products.add_product" %></h4>
      </div>
      <%= form_for(@product, url: admin_products_path , html: { id: "formGroup" }) do |p| %>
      <div class="modal-body body-add-product">
        <div class="form-group">
          <div class="preview col-md-6">
            <label for="exampleInputFile"><%= t "admin.products.add_picture" %></label>
              <div >
                <%= p.file_field :image%>
              </div>
          </div>
          <div class="preview col-md-6">
            <form>
              <div class="form-group row">
                <label class="col-sm-2 col-form-label "><%= t "admin.products.category_id" %></label>
                <div class=" text col-sm-10">
                  <%= p.text_field :category_id, class: "input-text" %>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-sm-2 col-form-label"><%= t "admin.products.name" %></label>
                <div class="col-sm-10">
                <%= p.text_field :name, class: "input-text" %>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-sm-2 col-form-label"><%= t "admin.products.price" %></label>
                <div class="col-sm-10">
                <%= p.text_field :price, class: "input-text" %>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-sm-2 col-form-label"><%= t "admin.products.renting_fee" %></label>
                <div class="col-sm-10">
                <%= p.text_field :renting_fee, class: "input-text" %>
                </div>
              </div>
              <div class="form-group">
                <button type="button" class="btn-back btn btn-default pull-left" data-dismiss="modal"><%= t "admin.products.btn_back" %></button>
                <%= p.submit t("admin.products.btn_save"), type:"submit", id:"button", class:"btn-save btn btn-primary" %>
              </div>
            </form>
          </div>
        </div>
      </div>
      <script type="text/javascript">
        $(function(){
          var notice = "<%= !flash[:notice].nil? ? flash[:notice].first : '' %>"
          var type = "<%= !flash[:notice].nil? ? flash[:notice].last : '' %>"
          $.notify(notice, type );
        })
      </script>
    <% end %>
  </div>
</div>

app/views/admin/products/_product.html.erb
<% @products.each_with_index  do |item, index| %>
  <% if (index == 0 || index % 5 == 0) %>
    <div class="row row-item">
    <% end %>
    <div id="product_<%= @product.id %>" class="col-md-3 col-sm-6 col-xs-12 item">
      <a href="#" class="link">
        <div class="image" style="background-image: url(<%= item.image %>);">
          <span class="title">
            <p class="text text-price"><%= item.price %></p>
            <p class="text" id-name="<%= item.id %>"><%= item.name %></p>
          </span>
        </div>
        <div class="btn-group">
          <button class="btn btn-default delete bt-delete" idbutton="<%= item.id %>">
            <i class="fa fa-trash"></i>
          </button>
          <%= link_to edit_admin_product_path(item), class: "btn btn-default edit", remote: true do %>
          <i class="fa fa-edit "></i>
        <%end%>
      </div>
    </a>
  </div>
  <% if ((index + 1) % 5 == 0 || index == (products.size - 1)) %>
  </div>
<% end %>
<% end %>
<div class="row paginate">
<%= paginate products, theme: "twitter-bootstrap-4" %>
</div>
<script type="text/javascript">
$(function () {
  var notice = "<%= !flash[:notice].nil? ? flash[:notice].first : '' %>"
  var type = "<%= !flash[:notice].nil? ? flash[:notice].last : '' %>"
  $.notify(notice, type);
  <% flash[:notice] = "" %>
})
</script>

app/views/admin/products/_product_size.html.erb
<div>
  <div class="form-group row">
    <%= product_size.label :Size, class: "col-sm-2 col-form-label" %>
    <div class="text col-sm-10">
      <%= product_size.select :size_id, @sizes.collect {|u| [u.name, u.id]},
        {}, {class: "select-size"} %>
      <label class=" col-form-label label-color"><%= t "admin.products.color" %></label>
      <%= product_size.text_field :color, class: "input-text text-color" %>
      <label class=" col-form-label "><%= t "admin.products.amount" %></label>
      <%= product_size.text_field :quantity, class: "input-text text-amount" %>
    </div>
  </div>
</div>

app/views/admin/products/destroy.js.erb
$("#product").html("<%= j render 'product', products: @products %>");

app/views/admin/products/new.js.erb
$('.load-form').html('<%= j render("form") %>');
$('#modal-default').modal("show");
$(".new_product").validate({
  errorPlacement: function(error, element) {
    error.insertAfter(element);
  },
  rules: {
    "product[image]": {
      required: true,
    },
    "product[name]": {
      required: true,
    },
    "product[price]": {
      required: true,
      number: true,
      min: 0,
    },
    "product[renting_fee]": {
      required: true,
      number: true,
      min: 0,
    }
  },
  messages: {
    "product[image]": {
      required: "xin chọn ảnh",
    },
    "product[name]": {
      required: "tên không hợp lệ!",
    },
    "product[price]": {
      required: "giá không hợp lệ",
      number: "phải là số",
      min: "không được âm",
    },
    "product[renting_fee]": {
      required: "phí thuê không hợp lệ",
      number: "phải là số",
      min: "không được âm",
    }
  },
  onfocusout: function(element) {
      this.element(element);
    }
})