config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  namespace :admin do
    root "admins#login"
    resources :admins
    resources :categories
    resources :products
    resources :bills
    resources :product_bills
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  has_many :product_bills
  scope :find_by_bill, -> bill_id {where bill_id: bill_id}
  scope :get_bill_duration, -> end_renting{
    (end_renting - Date.current()).to_s.split("/")[0].to_i
  }
end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :items

def add_item(product_id)
    if item
        # increase the quantity of product in cart
        count + 1
        save
    else
        # product does not exist in cart
        product = Product.find(product_id)
        items << product
    end
    save
end

def total_price
    items.to_a.sum(&:full_price)
end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/system/categories/images/default-image.png"
    validates_attachment :image, presence: true
    do_not_validate_attachment_file_type :image
    validates :name, presence: true

    #apply default scope for all query of Category
    default_scope {where is_deleted: false}
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  scope :find_by_products, -> category_id {where category_id: category_id }
  has_many :product_sizes
  has_many :product_bills
  enum status: [:remove,:active]
  has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  accepts_nested_attributes_for :product_sizes,
  reject_if: proc { |attrs| attrs[:size_id].blank? }
end

app/models/product_bill.rb
class ProductBill < ApplicationRecord
  belongs_to :product
  belongs_to :bill
  belongs_to :size
  scope :find_by_billid, -> id {where bill_id: id }
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  belongs_to :product
  belongs_to :size
  # Attributes: color:string, quantity:integer, note:string
end

app/models/size.rb
class Size < ApplicationRecord
    has_many :product_sizes
    has_many :product_bills
    accepts_nested_attributes_for :product_sizes
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :bills
  scope :find_by_role,  -> role_number {where role: role_number}

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def show
    @bill = Bill.find_by id: params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def new
        @category = Category.new
    end

    def create
        @category = Category.new(params.require(:category).permit(:name, :image))
        @category.save
        redirect_to admin_category_path(@category)
    end

    def show
        @category = Category.find_by(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by id: params[:id]` 
end

app/helpers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/product_bills_helper.rb
module ProductBillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admins/login.html.erb
<DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.js"></script>
</head>
<body class="login">
  <div class="container">
    <div class="main-login main-center">
      <h1 align="center">INSAL</h1>
      <h4 align="center"> <%= t "admin.user_sign_in" %> </h4>
      <%= form_tag '/admin/admins', :method => 'post', :class => 'form-login' do %>
        <!-- EMAIL  -->
        <div class="form-group">
          <label for="name" class="cols-sm-2 control-label"> <%= t "admin.email" %> </label>
          <div class="cols-sm-10">
            <div class="input-group">
              <span id="input-group" class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
              <%= text_field_tag :email, params[:email],  type:"text", class:"form-control", id:"email"%>
            </div>
          </div>
        </div>
        <!-- PASSWORD  -->
        <div class="form-group">
          <label for="email" class="cols-sm-2 control-label"> <%= t "admin.password" %> </label>
          <div class="cols-sm-10">
            <div class="input-group">
              <span id="input-group" class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
              <%= password_field_tag :password, nil, type:"password", class:"form-control", id:"password"%>
              <!-- <input type="password" class="form-control" name="password" id="password"  placeholder="<%= t "admin.enter_password" %>"/>    -->
            </div>
          </div>
        </div>
        <div class="row" align="center">
          <a style="color: #ffffff; font-size: 15px;" href="/signup"> <%= t "admin.new_account" %> </a>
        </div>
        <div class="form-group">
          <%= submit_tag "Log In", type:"submit", id:"button", class:"btn btn-primary btn-lg btn-block login-button" %>
           <!--<button type="submit" id="button" class="btn btn-primary btn-lg btn-block login-button"> <%= t "admin.sign_in" %> </button>    -->
        </div>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/layouts/_header.html.erb
<header class="main-header">
  <a href="#" class="logo logo-insal">
    <span class="logo-mini"><b>IN</b>S</span>
    <span class="logo-lg"><b>IN</b>SAL</span>
  </a>
  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="input-group input-group--custom">
      <div class="input-group-btn">
        <button type="button" class="btn btn-danger"><%= t "layouts.action" %></button>
      </div>
      <input type="text" class="form-control">
    </div>
    <div class="navbar-custom-menu locate-logout">
      <ul class="nav navbar-nav">
        <li class="dropdown notifications-menu">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             <i class="fa fa-cart-plus cart-shop-icon"></i>
             <span class="label label-warning">10</span>
           </a>
           <ul class="dropdown-menu">
             <li class="header"><%= t "layouts.notice_item" %></li>
           </ul>
        </li>
        <li class="dropdown messages-menu">
          <%= link_to admin_admin_path(current_user), method: :delete, class:"dropdown-toggle" do %>
            <i class="fa fa-sign-out"></i>
            <span><%= t "layouts.log_out" %></span>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_side-bar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="active">
        <%= link_to admin_categories_path do %>
          <i class="fa fa-dashboard"></i> <span><%= t "layouts.categories" %></span>
          <span class="pull-right-container">
          </span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_bills_path do %>
          <i class="fa fa-files-o"></i>
          <span><%= t "layouts.bills" %></span>
          <span class="pull-right-container">
            <span class="label label-primary pull-right">4</span>
          </span>
        <% end %>
      </li>
      <li class="header"><%= t "layouts.insights" %></li>
      <li>
        <%= link_to admin_products_path do %>
           <i class="fa fa-circle-o text-red"></i>
          <span><%= t "layouts.products" %></span>
        <% end %>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsalPhanxipang</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsalPhanxipang</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
    <%= render  "layouts/header" %>
    <%= render  "layouts/side-bar" %>
    <div class="content-wrapper">
      <section class="content">
        <%= yield %>
      </section>
    </div>
    <%= render  "layouts/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<DOCTYPE html>
<html>
  <head>
    <title>InsalPhanxipang</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </div>
  </body>
</html>

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsalPhanxipang</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "layouts/header" %>
    <div>
      <div class="col-md-2 side-bar">
        <%= render  "layouts/side-bar" %></div>
      <div class="col-md-10">
        <%= yield %> 
      </div>
    </div>
  </body>
</html>